// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDONam1uU0PQYoKwH2T17P2F-Bd4FHaaIQ',
    appId: '1:956166002079:web:c066cd84737ad70a6019aa',
    messagingSenderId: '956166002079',
    projectId: 'halbzhera-quiz-app-62c6e',
    authDomain: 'halbzhera-quiz-app-62c6e.firebaseapp.com',
    storageBucket: 'halbzhera-quiz-app-62c6e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFDZpOAnUGwFEVkimp5Fe8_ywfEPZGUCA',
    appId: '1:956166002079:android:ff405227215fd84f6019aa',
    messagingSenderId: '956166002079',
    projectId: 'halbzhera-quiz-app-62c6e',
    storageBucket: 'halbzhera-quiz-app-62c6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUw_pzJ0uUoxKE80wSVnHu8HdyobXfMuw',
    appId: '1:956166002079:ios:d1f532b83043586f6019aa',
    messagingSenderId: '956166002079',
    projectId: 'halbzhera-quiz-app-62c6e',
    storageBucket: 'halbzhera-quiz-app-62c6e.firebasestorage.app',
    iosBundleId: 'com.example.halbzhera',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUw_pzJ0uUoxKE80wSVnHu8HdyobXfMuw',
    appId: '1:956166002079:ios:d1f532b83043586f6019aa',
    messagingSenderId: '956166002079',
    projectId: 'halbzhera-quiz-app-62c6e',
    storageBucket: 'halbzhera-quiz-app-62c6e.firebasestorage.app',
    iosBundleId: 'com.example.halbzhera',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDONam1uU0PQYoKwH2T17P2F-Bd4FHaaIQ',
    appId: '1:956166002079:web:3740bef22ba0ad116019aa',
    messagingSenderId: '956166002079',
    projectId: 'halbzhera-quiz-app-62c6e',
    authDomain: 'halbzhera-quiz-app-62c6e.firebaseapp.com',
    storageBucket: 'halbzhera-quiz-app-62c6e.firebasestorage.app',
  );

}